/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as UnconfirmedRouteImport } from './routes/unconfirmed';
import { Route as UnauthorizedRouteImport } from './routes/unauthorized';
import { Route as PendingStaffRouteImport } from './routes/pending-staff';
import { Route as EmailVerifiedRouteImport } from './routes/email-verified';
import { Route as ConfirmedRouteImport } from './routes/confirmed';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname';

const UnconfirmedRoute = UnconfirmedRouteImport.update({
  id: '/unconfirmed',
  path: '/unconfirmed',
  getParentRoute: () => rootRouteImport,
} as any);
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any);
const PendingStaffRoute = PendingStaffRouteImport.update({
  id: '/pending-staff',
  path: '/pending-staff',
  getParentRoute: () => rootRouteImport,
} as any);
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/email-verified': typeof EmailVerifiedRoute;
  '/pending-staff': typeof PendingStaffRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
  '/auth/$pathname': typeof AuthPathnameRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/email-verified': typeof EmailVerifiedRoute;
  '/pending-staff': typeof PendingStaffRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
  '/auth/$pathname': typeof AuthPathnameRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/email-verified': typeof EmailVerifiedRoute;
  '/pending-staff': typeof PendingStaffRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
  '/auth/$pathname': typeof AuthPathnameRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/confirmed'
    | '/email-verified'
    | '/pending-staff'
    | '/unauthorized'
    | '/unconfirmed'
    | '/auth/$pathname';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/confirmed'
    | '/email-verified'
    | '/pending-staff'
    | '/unauthorized'
    | '/unconfirmed'
    | '/auth/$pathname';
  id:
    | '__root__'
    | '/'
    | '/confirmed'
    | '/email-verified'
    | '/pending-staff'
    | '/unauthorized'
    | '/unconfirmed'
    | '/auth/$pathname';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConfirmedRoute: typeof ConfirmedRoute;
  EmailVerifiedRoute: typeof EmailVerifiedRoute;
  PendingStaffRoute: typeof PendingStaffRoute;
  UnauthorizedRoute: typeof UnauthorizedRoute;
  UnconfirmedRoute: typeof UnconfirmedRoute;
  AuthPathnameRoute: typeof AuthPathnameRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unconfirmed': {
      id: '/unconfirmed';
      path: '/unconfirmed';
      fullPath: '/unconfirmed';
      preLoaderRoute: typeof UnconfirmedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/unauthorized': {
      id: '/unauthorized';
      path: '/unauthorized';
      fullPath: '/unauthorized';
      preLoaderRoute: typeof UnauthorizedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pending-staff': {
      id: '/pending-staff';
      path: '/pending-staff';
      fullPath: '/pending-staff';
      preLoaderRoute: typeof PendingStaffRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/email-verified': {
      id: '/email-verified';
      path: '/email-verified';
      fullPath: '/email-verified';
      preLoaderRoute: typeof EmailVerifiedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirmed': {
      id: '/confirmed';
      path: '/confirmed';
      fullPath: '/confirmed';
      preLoaderRoute: typeof ConfirmedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/$pathname': {
      id: '/auth/$pathname';
      path: '/auth/$pathname';
      fullPath: '/auth/$pathname';
      preLoaderRoute: typeof AuthPathnameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmedRoute: ConfirmedRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  PendingStaffRoute: PendingStaffRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UnconfirmedRoute: UnconfirmedRoute,
  AuthPathnameRoute: AuthPathnameRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
