/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as UnconfirmedImport } from './routes/unconfirmed';
import { Route as ConfirmedImport } from './routes/confirmed';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const UnconfirmedRoute = UnconfirmedImport.update({
  id: '/unconfirmed',
  path: '/unconfirmed',
  getParentRoute: () => rootRoute,
} as any);

const ConfirmedRoute = ConfirmedImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/confirmed': {
      id: '/confirmed';
      path: '/confirmed';
      fullPath: '/confirmed';
      preLoaderRoute: typeof ConfirmedImport;
      parentRoute: typeof rootRoute;
    };
    '/unconfirmed': {
      id: '/unconfirmed';
      path: '/unconfirmed';
      fullPath: '/unconfirmed';
      preLoaderRoute: typeof UnconfirmedImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/confirmed': typeof ConfirmedRoute;
  '/unconfirmed': typeof UnconfirmedRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/confirmed' | '/unconfirmed';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/confirmed' | '/unconfirmed';
  id: '__root__' | '/' | '/confirmed' | '/unconfirmed';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConfirmedRoute: typeof ConfirmedRoute;
  UnconfirmedRoute: typeof UnconfirmedRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmedRoute: ConfirmedRoute,
  UnconfirmedRoute: UnconfirmedRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/confirmed",
        "/unconfirmed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/confirmed": {
      "filePath": "confirmed.tsx"
    },
    "/unconfirmed": {
      "filePath": "unconfirmed.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
